# Generated by Django 3.1.2 on 2020-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
