# Generated by Django 3.1.2 on 2020-11-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_box_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='time',
        ),
    ]
