# Generated by Django 3.1.2 on 2020-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
