# Generated by Django 3.1.2 on 2020-11-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20201125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='length',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription.box'),
            preserve_default=False,
        ),
    ]
