# Generated by Django 3.1.2 on 2020-11-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_length_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='length',
            name='box',
        ),
        migrations.AddField(
            model_name='box',
            name='length',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscription.length'),
            preserve_default=False,
        ),
    ]
