# Generated by Django 3.1.2 on 2020-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20201126_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='month_price_1',
        ),
        migrations.RemoveField(
            model_name='box',
            name='month_price_2',
        ),
        migrations.RemoveField(
            model_name='box',
            name='month_price_3',
        ),
    ]
