# Generated by Django 3.1.2 on 2020-11-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/countries'),
        ),
    ]
