# Generated by Django 3.1.2 on 2020-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='strip_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
