# Generated by Django 3.1.2 on 2020-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201118_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
