# Generated by Django 3.1.2 on 2020-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_allergy_advies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
